# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf2ba5050b2a68eae1004649e4e0699876322ecdd5ee444c7b9752d4cae7ed09e2124361f71ea58c2ff4048f41cba88b83386819cdd22e2301f29183a0c5a4ab

test:
  secret_key_base: dd67d1ad3ef4e88ae68d17711d03747e49dceb7144c83103fdf9a11e000de8e0e17ebee5df8f2f01d05d475de8b3e2868b246efb9eed5259279b4c5507b3a2df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
